# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import broadcast_pb2 as broadcast__pb2


class BroadcastStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send = channel.unary_unary(
        '/Broadcast/send',
        request_serializer=broadcast__pb2.SendRequest.SerializeToString,
        response_deserializer=broadcast__pb2.BroadcastMessage.FromString,
        )
    self.subscribe = channel.unary_stream(
        '/Broadcast/subscribe',
        request_serializer=broadcast__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=broadcast__pb2.BroadcastMessage.FromString,
        )


class BroadcastServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BroadcastServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=broadcast__pb2.SendRequest.FromString,
          response_serializer=broadcast__pb2.BroadcastMessage.SerializeToString,
      ),
      'subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.subscribe,
          request_deserializer=broadcast__pb2.SubscribeRequest.FromString,
          response_serializer=broadcast__pb2.BroadcastMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Broadcast', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
