# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='broadcast.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x62roadcast.proto\";\n\x0bSendRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\t.Category\"L\n\x10\x42roadcastMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\t.Category\"/\n\x10SubscribeRequest\x12\x1b\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\t.Category*:\n\x08\x43\x61tegory\x12\x07\n\x03\x41LL\x10\x00\x12\x08\n\x04MISC\x10\x01\x12\t\n\x05KUDOS\x10\x02\x12\x10\n\x0c\x41NNOUNCEMENT\x10\x03\x32m\n\tBroadcast\x12)\n\x04send\x12\x0c.SendRequest\x1a\x11.BroadcastMessage\"\x00\x12\x35\n\tsubscribe\x12\x11.SubscribeRequest\x1a\x11.BroadcastMessage\"\x00\x30\x01\x62\x06proto3')
)

_CATEGORY = _descriptor.EnumDescriptor(
  name='Category',
  full_name='Category',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KUDOS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOUNCEMENT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=207,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_CATEGORY)

Category = enum_type_wrapper.EnumTypeWrapper(_CATEGORY)
ALL = 0
MISC = 1
KUDOS = 2
ANNOUNCEMENT = 3



_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SendRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='SendRequest.category', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=78,
)


_BROADCASTMESSAGE = _descriptor.Descriptor(
  name='BroadcastMessage',
  full_name='BroadcastMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BroadcastMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='BroadcastMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='BroadcastMessage.category', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=156,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='SubscribeRequest.category', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=205,
)

_SENDREQUEST.fields_by_name['category'].enum_type = _CATEGORY
_BROADCASTMESSAGE.fields_by_name['category'].enum_type = _CATEGORY
_SUBSCRIBEREQUEST.fields_by_name['category'].enum_type = _CATEGORY
DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['BroadcastMessage'] = _BROADCASTMESSAGE
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.enum_types_by_name['Category'] = _CATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDREQUEST,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SendRequest)
  ))
_sym_db.RegisterMessage(SendRequest)

BroadcastMessage = _reflection.GeneratedProtocolMessageType('BroadcastMessage', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTMESSAGE,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:BroadcastMessage)
  ))
_sym_db.RegisterMessage(BroadcastMessage)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREQUEST,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeRequest)
  ))
_sym_db.RegisterMessage(SubscribeRequest)



_BROADCAST = _descriptor.ServiceDescriptor(
  name='Broadcast',
  full_name='Broadcast',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=267,
  serialized_end=376,
  methods=[
  _descriptor.MethodDescriptor(
    name='send',
    full_name='Broadcast.send',
    index=0,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_BROADCASTMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='Broadcast.subscribe',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_BROADCASTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROADCAST)

DESCRIPTOR.services_by_name['Broadcast'] = _BROADCAST

# @@protoc_insertion_point(module_scope)
